// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.28.3
// source: internal/proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime           int64                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Processor        string                 `protobuf:"bytes,4,opt,name=processor,proto3" json:"processor,omitempty"`
	DevType          string                 `protobuf:"bytes,5,opt,name=devType,proto3" json:"devType,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,6,opt,name=memoryTotalBytes,proto3" json:"memoryTotalBytes,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,7,opt,name=memoryUsedBytes,proto3" json:"memoryUsedBytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DevInfo) Reset() {
	*x = DevInfo{}
	mi := &file_internal_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevInfo) ProtoMessage() {}

func (x *DevInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevInfo.ProtoReflect.Descriptor instead.
func (*DevInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *DevInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DevInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DevInfo) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *DevInfo) GetProcessor() string {
	if x != nil {
		return x.Processor
	}
	return ""
}

func (x *DevInfo) GetDevType() string {
	if x != nil {
		return x.DevType
	}
	return ""
}

func (x *DevInfo) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *DevInfo) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

type Counter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InDrops       int64                  `protobuf:"varint,1,opt,name=inDrops,proto3" json:"inDrops,omitempty"`
	OutDrops      int64                  `protobuf:"varint,2,opt,name=outDrops,proto3" json:"outDrops,omitempty"`
	InPkts        int64                  `protobuf:"varint,3,opt,name=inPkts,proto3" json:"inPkts,omitempty"`
	InBytes       int64                  `protobuf:"varint,4,opt,name=inBytes,proto3" json:"inBytes,omitempty"`
	InErr         int64                  `protobuf:"varint,5,opt,name=inErr,proto3" json:"inErr,omitempty"`
	OutPkts       int64                  `protobuf:"varint,6,opt,name=outPkts,proto3" json:"outPkts,omitempty"`
	OutBytes      int64                  `protobuf:"varint,7,opt,name=outBytes,proto3" json:"outBytes,omitempty"`
	OutErr        int64                  `protobuf:"varint,8,opt,name=outErr,proto3" json:"outErr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counter) Reset() {
	*x = Counter{}
	mi := &file_internal_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *Counter) GetInDrops() int64 {
	if x != nil {
		return x.InDrops
	}
	return 0
}

func (x *Counter) GetOutDrops() int64 {
	if x != nil {
		return x.OutDrops
	}
	return 0
}

func (x *Counter) GetInPkts() int64 {
	if x != nil {
		return x.InPkts
	}
	return 0
}

func (x *Counter) GetInBytes() int64 {
	if x != nil {
		return x.InBytes
	}
	return 0
}

func (x *Counter) GetInErr() int64 {
	if x != nil {
		return x.InErr
	}
	return 0
}

func (x *Counter) GetOutPkts() int64 {
	if x != nil {
		return x.OutPkts
	}
	return 0
}

func (x *Counter) GetOutBytes() int64 {
	if x != nil {
		return x.OutBytes
	}
	return 0
}

func (x *Counter) GetOutErr() int64 {
	if x != nil {
		return x.OutErr
	}
	return 0
}

type L2Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NameOriginal  string                 `protobuf:"bytes,2,opt,name=nameOriginal,proto3" json:"nameOriginal,omitempty"`
	IfName        string                 `protobuf:"bytes,3,opt,name=ifName,proto3" json:"ifName,omitempty"`
	Disabled      string                 `protobuf:"bytes,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Running       string                 `protobuf:"bytes,5,opt,name=running,proto3" json:"running,omitempty"`
	Mac           string                 `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	Mtu           int32                  `protobuf:"varint,7,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Counter       *Counter               `protobuf:"bytes,9,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2Interface) Reset() {
	*x = L2Interface{}
	mi := &file_internal_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Interface) ProtoMessage() {}

func (x *L2Interface) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Interface.ProtoReflect.Descriptor instead.
func (*L2Interface) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *L2Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L2Interface) GetNameOriginal() string {
	if x != nil {
		return x.NameOriginal
	}
	return ""
}

func (x *L2Interface) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *L2Interface) GetDisabled() string {
	if x != nil {
		return x.Disabled
	}
	return ""
}

func (x *L2Interface) GetRunning() string {
	if x != nil {
		return x.Running
	}
	return ""
}

func (x *L2Interface) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *L2Interface) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *L2Interface) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *L2Interface) GetCounter() *Counter {
	if x != nil {
		return x.Counter
	}
	return nil
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          []*Stat                `protobuf:"bytes,1,rep,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_internal_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *Stats) GetStat() []*Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevInfo       *DevInfo               `protobuf:"bytes,1,opt,name=devInfo,proto3" json:"devInfo,omitempty"`
	L2Interface   []*L2Interface         `protobuf:"bytes,2,rep,name=l2Interface,proto3" json:"l2Interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_internal_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *Stat) GetDevInfo() *DevInfo {
	if x != nil {
		return x.DevInfo
	}
	return nil
}

func (x *Stat) GetL2Interface() []*L2Interface {
	if x != nil {
		return x.L2Interface
	}
	return nil
}

type AddStatsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStatsRes) Reset() {
	*x = AddStatsRes{}
	mi := &file_internal_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatsRes) ProtoMessage() {}

func (x *AddStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatsRes.ProtoReflect.Descriptor instead.
func (*AddStatsRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *AddStatsRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetStatsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRes) Reset() {
	*x = GetStatsRes{}
	mi := &file_internal_proto_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRes) ProtoMessage() {}

func (x *GetStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRes.ProtoReflect.Descriptor instead.
func (*GetStatsRes) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsRes) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReq) Reset() {
	*x = GetStatsReq{}
	mi := &file_internal_proto_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReq) ProtoMessage() {}

func (x *GetStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReq.ProtoReflect.Descriptor instead.
func (*GetStatsReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatsReq) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_internal_proto_stats_proto protoreflect.FileDescriptor

var file_internal_proto_stats_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe5, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x76, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x55, 0x73, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0xd5, 0x01, 0x0a, 0x07,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x44, 0x72, 0x6f,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6e, 0x44, 0x72, 0x6f, 0x70,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x6e, 0x50, 0x6b, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69,
	0x6e, 0x50, 0x6b, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x45, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x69, 0x6e, 0x45, 0x72, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x50, 0x6b, 0x74, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x50, 0x6b, 0x74, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x45, 0x72, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x45, 0x72, 0x72, 0x22, 0x83, 0x02, 0x0a, 0x0b, 0x4c, 0x32, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e,
	0x61, 0x6d, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x66, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x74, 0x75, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x28, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73,
	0x74, 0x61, 0x74, 0x22, 0x66, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x64,
	0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65,
	0x76, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x0b, 0x6c, 0x32, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x32, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x0b,
	0x6c, 0x32, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x41,
	0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x31, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x69, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x2c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_stats_proto_rawDescOnce sync.Once
	file_internal_proto_stats_proto_rawDescData = file_internal_proto_stats_proto_rawDesc
)

func file_internal_proto_stats_proto_rawDescGZIP() []byte {
	file_internal_proto_stats_proto_rawDescOnce.Do(func() {
		file_internal_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_stats_proto_rawDescData)
	})
	return file_internal_proto_stats_proto_rawDescData
}

var file_internal_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_stats_proto_goTypes = []any{
	(*DevInfo)(nil),     // 0: proto.DevInfo
	(*Counter)(nil),     // 1: proto.Counter
	(*L2Interface)(nil), // 2: proto.L2Interface
	(*Stats)(nil),       // 3: proto.Stats
	(*Stat)(nil),        // 4: proto.Stat
	(*AddStatsRes)(nil), // 5: proto.AddStatsRes
	(*GetStatsRes)(nil), // 6: proto.GetStatsRes
	(*GetStatsReq)(nil), // 7: proto.GetStatsReq
}
var file_internal_proto_stats_proto_depIdxs = []int32{
	1, // 0: proto.L2Interface.counter:type_name -> proto.Counter
	4, // 1: proto.Stats.stat:type_name -> proto.Stat
	0, // 2: proto.Stat.devInfo:type_name -> proto.DevInfo
	2, // 3: proto.Stat.l2Interface:type_name -> proto.L2Interface
	3, // 4: proto.GetStatsRes.stats:type_name -> proto.Stats
	3, // 5: proto.Users.AddStats:input_type -> proto.Stats
	7, // 6: proto.Users.GetStats:input_type -> proto.GetStatsReq
	5, // 7: proto.Users.AddStats:output_type -> proto.AddStatsRes
	6, // 8: proto.Users.GetStats:output_type -> proto.GetStatsRes
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_stats_proto_init() }
func file_internal_proto_stats_proto_init() {
	if File_internal_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_stats_proto_goTypes,
		DependencyIndexes: file_internal_proto_stats_proto_depIdxs,
		MessageInfos:      file_internal_proto_stats_proto_msgTypes,
	}.Build()
	File_internal_proto_stats_proto = out.File
	file_internal_proto_stats_proto_rawDesc = nil
	file_internal_proto_stats_proto_goTypes = nil
	file_internal_proto_stats_proto_depIdxs = nil
}
